# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b'profile_pics/%Y-%m-%d/', verbose_name=b'Profile picture'),
        ),
    ]
